name: Carpenter Workflow to Build and Push Image
on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      quay_img_exp:
        required: true
        type: string
      image_name:
        required: true
        type: string
      github_namespace:
        required: false
        type: string     
    secrets:     
      GITHUB_PASSWORD:
      QUAY_NAMESPACE:
      QUAY_USERNAME:
      QUAY_PASSWORD:
  push:
    branches:
      - "**"
  release:
    types:
      - published
  
jobs:
  carpenter-build:
    name: Build ${{ github.ref_name }} from ${{ github.event_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Set ENV
        run: |
          echo "IMAGE_TAG= $image_tag" >> $GITHUB_ENV
          echo "QUAY_IMG_EXP= $quay_img_exp" >> $GITHUB_ENV
          echo "IMAGE_NAME= $image_name" >> $GITHUB_ENV
          echo "GITHUB_PASSWORD:${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "GITHUB_NAMESPACE= $github_namespace" >> $GITHUB_ENV
          echo "QUAY_NAMESPACE:${{ secrets.QUAY_NAMESPACE }}" >> $GITHUB_ENV
          echo "QUAY_USERNAME:${{ secrets.QUAY_USERNAME }} >> $GITHUB_ENV
          echo "QUAY_PASSWORD:${{ secrets.QUAY_PASSWORD }}" >> $GITHUB_ENV
      - name: Set image tag for release
        if: github.event_name == 'release'
        run: |
          echo "IMAGE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set image tag and expiration for dev
        if: github.ref != 'refs/heads/main' && github.event_name != 'release'
        run: |
          export commit_hash=${{ github.sha }}
          echo "IMAGE_TAG=${GITHUB_REF##*/}_${commit_hash:0:7}" >> $GITHUB_ENV
          echo "QUAY_IMG_EXP=90d" >> $GITHUB_ENV
      - name: Checkout this project
        uses: actions/checkout@v3
      - name: Carpenter build
        uses: arcalot/arcaflow-plugin-image-builder@main
        with:
          args: build --build --push
