name: Build
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve code coverage
        run: |
          echo "${{ inputs.image_name }}:${{ inputs.image_tag }}"
          docker create --name temp "${{ inputs.image_name }}:${{ inputs.image_tag }}"
          docker cp temp:/htmlcov .
          docker rm temp
          pip install html2text
          html2text --ignore-images --ignore-links -b 0 htmlcov/index.html >> $GITHUB_STEP_SUMMARY
      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: htmlcov
          if-no-files-found: error
